spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
  flyway:
    enabled: true

cache:
  names: [tasks, task]
  maximum-size: 100
  expire-after-write-minutes: 10
